### ISSUE TITLE
Pagination helper flattens TOO much

### ISSUE THREAD

**Issue by eaceaser** [fauna/faunadb-ruby#196]
When you are paginating over a set that contains arrays, the pagination helper flattens those arrays too, so it ends up emitting [a1, b1, a2, b2,....] as opposed to [[a1, b1], [a2, b2], ....]

**Comment by ashfire908** [comment]
I'm unable to reproduce this. Do you have an example?

**Comment by eaceaser** [comment]
i think this was invalid
